repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black amz_tango_card_scraper/
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort amz_tango_card_scraper/
        language: system
        always_run: true
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run flake8 amz_tango_card_scraper/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy amz_tango_card_scraper/
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest tests/
        language: system
        always_run: true
        pass_filenames: false
      - id: create-requirements-txt
        name: create-requirements-txt
        entry: poetry export -f requirements.txt --output requirements.txt --without-hashes
        language: system
        always_run: true
        pass_filenames: false
