repos:
  - repo: local
    hooks:
      - id: black
        name: black
        entry: poetry run black src/
        language: system
        always_run: true
        pass_filenames: false
      - id: isort
        name: isort
        entry: poetry run isort src/
        language: system
        always_run: true
        pass_filenames: false
      - id: flake8
        name: flake8
        entry: poetry run flake8 src/
        language: system
        always_run: true
        pass_filenames: false
      - id: mypy
        name: mypy
        entry: poetry run mypy src/
        language: system
        always_run: true
        pass_filenames: false
      - id: pytest
        name: pytest
        entry: poetry run pytest tests/
        language: system
        always_run: true
        pass_filenames: false
