# Configuration file for AMZ Tango Card Scrapper

# Gmail account information for Amazon Tango Card email scraping
# Note: You must create an app password for your Google account: https://myaccount.google.com/apppasswords
gmail:
  email: example@gmail.com
  app_password: myGoogleAppPassword123

# Amazon account information for automatic code redemption
# This is only required if you want to automatically redeem Amazon codes, otherwise leave it as is
# Note: You must enable 2FA for your Amazon account with OTP and put that generator in the OTP field: https://www.amazon.com/gp/help/customer/display.html?nodeId=G3PWZPU52FKN7PW4
amazon:
  email: example@email.com
  password: myAmazonPassword456
  otp: myAmazonOTP789

# Email from field
# Note: This is used to filter out emails that can contain Amazon Tango Card codes
from:
  - microsoftrewards@email.microsoftrewards.com
  - example@gmail.com
  - example2@yahoo.com

# Script configuration parameters
script:
  no_images: True # Set to True to disable image loading in Selenium
  headless: True # Set to True to run Selenium in headless mode
  trash: False # Set to True to move checked emails to trash
  redeem_amz: True # Set to True to redeem Amazon codes automatically
  no_webdriver_manager: False # Set to True to disable webdriver_manager
